/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUnauthorizedRouteImport } from './routes/app.unauthorized'
import { Route as AppTeacherWorkshopsRouteImport } from './routes/app.teacher.workshops'
import { Route as AppTeacherGradebookRouteImport } from './routes/app.teacher.gradebook'
import { Route as AppTeacherCoursesRouteImport } from './routes/app.teacher.courses'
import { Route as AppTeacherAttendanceRouteImport } from './routes/app.teacher.attendance'
import { Route as AppStudentWorkshopsRouteImport } from './routes/app.student.workshops'
import { Route as AppStudentGradesRouteImport } from './routes/app.student.grades'
import { Route as AppStudentExamsRouteImport } from './routes/app.student.exams'
import { Route as AppStudentCoursesRouteImport } from './routes/app.student.courses'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminCoursesRouteImport } from './routes/app.admin.courses'
import { Route as AppTeacherExamsIndexRouteImport } from './routes/app.teacher.exams.index'
import { Route as AppTeacherMonitorExamIdRouteImport } from './routes/app.teacher.monitor.$examId'
import { Route as AppTeacherGradingCourseIdRouteImport } from './routes/app.teacher.grading.$courseId'
import { Route as AppTeacherExamsExamIdRouteImport } from './routes/app.teacher.exams.$examId'
import { Route as AppStudentWorkshopWorkshopIdRouteImport } from './routes/app.student.workshop.$workshopId'
import { Route as AppStudentTakeExamIdRouteImport } from './routes/app.student.take.$examId'
import { Route as AppStudentReviewExamIdRouteImport } from './routes/app.student.review.$examId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherWorkshopsRoute = AppTeacherWorkshopsRouteImport.update({
  id: '/teacher/workshops',
  path: '/teacher/workshops',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherGradebookRoute = AppTeacherGradebookRouteImport.update({
  id: '/teacher/gradebook',
  path: '/teacher/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherCoursesRoute = AppTeacherCoursesRouteImport.update({
  id: '/teacher/courses',
  path: '/teacher/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherAttendanceRoute = AppTeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentWorkshopsRoute = AppStudentWorkshopsRouteImport.update({
  id: '/student/workshops',
  path: '/student/workshops',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentGradesRoute = AppStudentGradesRouteImport.update({
  id: '/student/grades',
  path: '/student/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentExamsRoute = AppStudentExamsRouteImport.update({
  id: '/student/exams',
  path: '/student/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentCoursesRoute = AppStudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCoursesRoute = AppAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherExamsIndexRoute = AppTeacherExamsIndexRouteImport.update({
  id: '/teacher/exams/',
  path: '/teacher/exams/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherMonitorExamIdRoute = AppTeacherMonitorExamIdRouteImport.update({
  id: '/teacher/monitor/$examId',
  path: '/teacher/monitor/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherGradingCourseIdRoute =
  AppTeacherGradingCourseIdRouteImport.update({
    id: '/teacher/grading/$courseId',
    path: '/teacher/grading/$courseId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTeacherExamsExamIdRoute = AppTeacherExamsExamIdRouteImport.update({
  id: '/teacher/exams/$examId',
  path: '/teacher/exams/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentWorkshopWorkshopIdRoute =
  AppStudentWorkshopWorkshopIdRouteImport.update({
    id: '/student/workshop/$workshopId',
    path: '/student/workshop/$workshopId',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentTakeExamIdRoute = AppStudentTakeExamIdRouteImport.update({
  id: '/student/take/$examId',
  path: '/student/take/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentReviewExamIdRoute = AppStudentReviewExamIdRouteImport.update({
  id: '/student/review/$examId',
  path: '/student/review/$examId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/exams': typeof AppStudentExamsRoute
  '/app/student/grades': typeof AppStudentGradesRoute
  '/app/student/workshops': typeof AppStudentWorkshopsRoute
  '/app/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/app/teacher/courses': typeof AppTeacherCoursesRoute
  '/app/teacher/gradebook': typeof AppTeacherGradebookRoute
  '/app/teacher/workshops': typeof AppTeacherWorkshopsRoute
  '/app/student/review/$examId': typeof AppStudentReviewExamIdRoute
  '/app/student/take/$examId': typeof AppStudentTakeExamIdRoute
  '/app/student/workshop/$workshopId': typeof AppStudentWorkshopWorkshopIdRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/grading/$courseId': typeof AppTeacherGradingCourseIdRoute
  '/app/teacher/monitor/$examId': typeof AppTeacherMonitorExamIdRoute
  '/app/teacher/exams/': typeof AppTeacherExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/exams': typeof AppStudentExamsRoute
  '/app/student/grades': typeof AppStudentGradesRoute
  '/app/student/workshops': typeof AppStudentWorkshopsRoute
  '/app/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/app/teacher/courses': typeof AppTeacherCoursesRoute
  '/app/teacher/gradebook': typeof AppTeacherGradebookRoute
  '/app/teacher/workshops': typeof AppTeacherWorkshopsRoute
  '/app/student/review/$examId': typeof AppStudentReviewExamIdRoute
  '/app/student/take/$examId': typeof AppStudentTakeExamIdRoute
  '/app/student/workshop/$workshopId': typeof AppStudentWorkshopWorkshopIdRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/grading/$courseId': typeof AppTeacherGradingCourseIdRoute
  '/app/teacher/monitor/$examId': typeof AppTeacherMonitorExamIdRoute
  '/app/teacher/exams': typeof AppTeacherExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/exams': typeof AppStudentExamsRoute
  '/app/student/grades': typeof AppStudentGradesRoute
  '/app/student/workshops': typeof AppStudentWorkshopsRoute
  '/app/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/app/teacher/courses': typeof AppTeacherCoursesRoute
  '/app/teacher/gradebook': typeof AppTeacherGradebookRoute
  '/app/teacher/workshops': typeof AppTeacherWorkshopsRoute
  '/app/student/review/$examId': typeof AppStudentReviewExamIdRoute
  '/app/student/take/$examId': typeof AppStudentTakeExamIdRoute
  '/app/student/workshop/$workshopId': typeof AppStudentWorkshopWorkshopIdRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/grading/$courseId': typeof AppTeacherGradingCourseIdRoute
  '/app/teacher/monitor/$examId': typeof AppTeacherMonitorExamIdRoute
  '/app/teacher/exams/': typeof AppTeacherExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/unauthorized'
    | '/app/'
    | '/app/admin/courses'
    | '/app/admin/users'
    | '/app/student/courses'
    | '/app/student/exams'
    | '/app/student/grades'
    | '/app/student/workshops'
    | '/app/teacher/attendance'
    | '/app/teacher/courses'
    | '/app/teacher/gradebook'
    | '/app/teacher/workshops'
    | '/app/student/review/$examId'
    | '/app/student/take/$examId'
    | '/app/student/workshop/$workshopId'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/grading/$courseId'
    | '/app/teacher/monitor/$examId'
    | '/app/teacher/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/unauthorized'
    | '/app'
    | '/app/admin/courses'
    | '/app/admin/users'
    | '/app/student/courses'
    | '/app/student/exams'
    | '/app/student/grades'
    | '/app/student/workshops'
    | '/app/teacher/attendance'
    | '/app/teacher/courses'
    | '/app/teacher/gradebook'
    | '/app/teacher/workshops'
    | '/app/student/review/$examId'
    | '/app/student/take/$examId'
    | '/app/student/workshop/$workshopId'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/grading/$courseId'
    | '/app/teacher/monitor/$examId'
    | '/app/teacher/exams'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/unauthorized'
    | '/app/'
    | '/app/admin/courses'
    | '/app/admin/users'
    | '/app/student/courses'
    | '/app/student/exams'
    | '/app/student/grades'
    | '/app/student/workshops'
    | '/app/teacher/attendance'
    | '/app/teacher/courses'
    | '/app/teacher/gradebook'
    | '/app/teacher/workshops'
    | '/app/student/review/$examId'
    | '/app/student/take/$examId'
    | '/app/student/workshop/$workshopId'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/grading/$courseId'
    | '/app/teacher/monitor/$examId'
    | '/app/teacher/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unauthorized': {
      id: '/app/unauthorized'
      path: '/unauthorized'
      fullPath: '/app/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/workshops': {
      id: '/app/teacher/workshops'
      path: '/teacher/workshops'
      fullPath: '/app/teacher/workshops'
      preLoaderRoute: typeof AppTeacherWorkshopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/gradebook': {
      id: '/app/teacher/gradebook'
      path: '/teacher/gradebook'
      fullPath: '/app/teacher/gradebook'
      preLoaderRoute: typeof AppTeacherGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/courses': {
      id: '/app/teacher/courses'
      path: '/teacher/courses'
      fullPath: '/app/teacher/courses'
      preLoaderRoute: typeof AppTeacherCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/attendance': {
      id: '/app/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/app/teacher/attendance'
      preLoaderRoute: typeof AppTeacherAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/workshops': {
      id: '/app/student/workshops'
      path: '/student/workshops'
      fullPath: '/app/student/workshops'
      preLoaderRoute: typeof AppStudentWorkshopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/grades': {
      id: '/app/student/grades'
      path: '/student/grades'
      fullPath: '/app/student/grades'
      preLoaderRoute: typeof AppStudentGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/exams': {
      id: '/app/student/exams'
      path: '/student/exams'
      fullPath: '/app/student/exams'
      preLoaderRoute: typeof AppStudentExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/courses': {
      id: '/app/student/courses'
      path: '/student/courses'
      fullPath: '/app/student/courses'
      preLoaderRoute: typeof AppStudentCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/courses': {
      id: '/app/admin/courses'
      path: '/admin/courses'
      fullPath: '/app/admin/courses'
      preLoaderRoute: typeof AppAdminCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/exams/': {
      id: '/app/teacher/exams/'
      path: '/teacher/exams'
      fullPath: '/app/teacher/exams/'
      preLoaderRoute: typeof AppTeacherExamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/monitor/$examId': {
      id: '/app/teacher/monitor/$examId'
      path: '/teacher/monitor/$examId'
      fullPath: '/app/teacher/monitor/$examId'
      preLoaderRoute: typeof AppTeacherMonitorExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/grading/$courseId': {
      id: '/app/teacher/grading/$courseId'
      path: '/teacher/grading/$courseId'
      fullPath: '/app/teacher/grading/$courseId'
      preLoaderRoute: typeof AppTeacherGradingCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/exams/$examId': {
      id: '/app/teacher/exams/$examId'
      path: '/teacher/exams/$examId'
      fullPath: '/app/teacher/exams/$examId'
      preLoaderRoute: typeof AppTeacherExamsExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/workshop/$workshopId': {
      id: '/app/student/workshop/$workshopId'
      path: '/student/workshop/$workshopId'
      fullPath: '/app/student/workshop/$workshopId'
      preLoaderRoute: typeof AppStudentWorkshopWorkshopIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/take/$examId': {
      id: '/app/student/take/$examId'
      path: '/student/take/$examId'
      fullPath: '/app/student/take/$examId'
      preLoaderRoute: typeof AppStudentTakeExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/review/$examId': {
      id: '/app/student/review/$examId'
      path: '/student/review/$examId'
      fullPath: '/app/student/review/$examId'
      preLoaderRoute: typeof AppStudentReviewExamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCoursesRoute: typeof AppAdminCoursesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppStudentCoursesRoute: typeof AppStudentCoursesRoute
  AppStudentExamsRoute: typeof AppStudentExamsRoute
  AppStudentGradesRoute: typeof AppStudentGradesRoute
  AppStudentWorkshopsRoute: typeof AppStudentWorkshopsRoute
  AppTeacherAttendanceRoute: typeof AppTeacherAttendanceRoute
  AppTeacherCoursesRoute: typeof AppTeacherCoursesRoute
  AppTeacherGradebookRoute: typeof AppTeacherGradebookRoute
  AppTeacherWorkshopsRoute: typeof AppTeacherWorkshopsRoute
  AppStudentReviewExamIdRoute: typeof AppStudentReviewExamIdRoute
  AppStudentTakeExamIdRoute: typeof AppStudentTakeExamIdRoute
  AppStudentWorkshopWorkshopIdRoute: typeof AppStudentWorkshopWorkshopIdRoute
  AppTeacherExamsExamIdRoute: typeof AppTeacherExamsExamIdRoute
  AppTeacherGradingCourseIdRoute: typeof AppTeacherGradingCourseIdRoute
  AppTeacherMonitorExamIdRoute: typeof AppTeacherMonitorExamIdRoute
  AppTeacherExamsIndexRoute: typeof AppTeacherExamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUnauthorizedRoute: AppUnauthorizedRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminCoursesRoute: AppAdminCoursesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppStudentCoursesRoute: AppStudentCoursesRoute,
  AppStudentExamsRoute: AppStudentExamsRoute,
  AppStudentGradesRoute: AppStudentGradesRoute,
  AppStudentWorkshopsRoute: AppStudentWorkshopsRoute,
  AppTeacherAttendanceRoute: AppTeacherAttendanceRoute,
  AppTeacherCoursesRoute: AppTeacherCoursesRoute,
  AppTeacherGradebookRoute: AppTeacherGradebookRoute,
  AppTeacherWorkshopsRoute: AppTeacherWorkshopsRoute,
  AppStudentReviewExamIdRoute: AppStudentReviewExamIdRoute,
  AppStudentTakeExamIdRoute: AppStudentTakeExamIdRoute,
  AppStudentWorkshopWorkshopIdRoute: AppStudentWorkshopWorkshopIdRoute,
  AppTeacherExamsExamIdRoute: AppTeacherExamsExamIdRoute,
  AppTeacherGradingCourseIdRoute: AppTeacherGradingCourseIdRoute,
  AppTeacherMonitorExamIdRoute: AppTeacherMonitorExamIdRoute,
  AppTeacherExamsIndexRoute: AppTeacherExamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
