/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminCoursesRouteImport } from './routes/app.admin.courses'
import { Route as AppTeacherExamsIndexRouteImport } from './routes/app.teacher.exams.index'
import { Route as AppTeacherExamsExamIdRouteImport } from './routes/app.teacher.exams.$examId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCoursesRoute = AppAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherExamsIndexRoute = AppTeacherExamsIndexRouteImport.update({
  id: '/teacher/exams/',
  path: '/teacher/exams/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherExamsExamIdRoute = AppTeacherExamsExamIdRouteImport.update({
  id: '/teacher/exams/$examId',
  path: '/teacher/exams/$examId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/exams/': typeof AppTeacherExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/exams': typeof AppTeacherExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/exams/': typeof AppTeacherExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/'
    | '/app/admin/courses'
    | '/app/admin/users'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/admin/courses'
    | '/app/admin/users'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/exams'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/'
    | '/app/admin/courses'
    | '/app/admin/users'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/courses': {
      id: '/app/admin/courses'
      path: '/admin/courses'
      fullPath: '/app/admin/courses'
      preLoaderRoute: typeof AppAdminCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/exams/': {
      id: '/app/teacher/exams/'
      path: '/teacher/exams'
      fullPath: '/app/teacher/exams/'
      preLoaderRoute: typeof AppTeacherExamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/exams/$examId': {
      id: '/app/teacher/exams/$examId'
      path: '/teacher/exams/$examId'
      fullPath: '/app/teacher/exams/$examId'
      preLoaderRoute: typeof AppTeacherExamsExamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCoursesRoute: typeof AppAdminCoursesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppTeacherExamsExamIdRoute: typeof AppTeacherExamsExamIdRoute
  AppTeacherExamsIndexRoute: typeof AppTeacherExamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminCoursesRoute: AppAdminCoursesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppTeacherExamsExamIdRoute: AppTeacherExamsExamIdRoute,
  AppTeacherExamsIndexRoute: AppTeacherExamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
