/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as VerifyShortCodeRouteImport } from './routes/verify.$shortCode'
import { Route as RetoPinRouteImport } from './routes/reto.$pin'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth.sso-callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthConfirmEmailChangeRouteImport } from './routes/auth.confirm-email-change'
import { Route as AuthCancelEmailChangeRouteImport } from './routes/auth.cancel-email-change'
import { Route as AppVideosRouteImport } from './routes/app.videos'
import { Route as AppUnauthorizedRouteImport } from './routes/app.unauthorized'
import { Route as AppTrashRouteImport } from './routes/app.trash'
import { Route as AppPrivacyRouteImport } from './routes/app.privacy'
import { Route as AppPreferencesRouteImport } from './routes/app.preferences'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppTeacherWorkshopsRouteImport } from './routes/app.teacher.workshops'
import { Route as AppTeacherStudentsRouteImport } from './routes/app.teacher.students'
import { Route as AppTeacherStatisticsRouteImport } from './routes/app.teacher.statistics'
import { Route as AppTeacherReportsRouteImport } from './routes/app.teacher.reports'
import { Route as AppTeacherQuestionBankRouteImport } from './routes/app.teacher.question-bank'
import { Route as AppTeacherProjectsRouteImport } from './routes/app.teacher.projects'
import { Route as AppTeacherPollsRouteImport } from './routes/app.teacher.polls'
import { Route as AppTeacherGradebookRouteImport } from './routes/app.teacher.gradebook'
import { Route as AppTeacherCoursesRouteImport } from './routes/app.teacher.courses'
import { Route as AppTeacherContentsRouteImport } from './routes/app.teacher.contents'
import { Route as AppTeacherCalendarRouteImport } from './routes/app.teacher.calendar'
import { Route as AppTeacherAuditLogsRouteImport } from './routes/app.teacher.audit-logs'
import { Route as AppTeacherAttendanceRouteImport } from './routes/app.teacher.attendance'
import { Route as AppTeacherAiPromptsRouteImport } from './routes/app.teacher.ai-prompts'
import { Route as AppTeacherAiCronRouteImport } from './routes/app.teacher.ai-cron'
import { Route as AppSuperadminTenantsRouteImport } from './routes/app.superadmin.tenants'
import { Route as AppSuperadminSystemRouteImport } from './routes/app.superadmin.system'
import { Route as AppSuperadminSupportRouteImport } from './routes/app.superadmin.support'
import { Route as AppSuperadminPricingCalculatorRouteImport } from './routes/app.superadmin.pricing-calculator'
import { Route as AppStudentWorkshopsRouteImport } from './routes/app.student.workshops'
import { Route as AppStudentProjectsRouteImport } from './routes/app.student.projects'
import { Route as AppStudentPollsRouteImport } from './routes/app.student.polls'
import { Route as AppStudentGradesRouteImport } from './routes/app.student.grades'
import { Route as AppStudentExamsRouteImport } from './routes/app.student.exams'
import { Route as AppStudentCoursesRouteImport } from './routes/app.student.courses'
import { Route as AppStudentCertificatesRouteImport } from './routes/app.student.certificates'
import { Route as AppStudentCalendarRouteImport } from './routes/app.student.calendar'
import { Route as AppStudentAttendanceRouteImport } from './routes/app.student.attendance'
import { Route as AppForumCourseIdRouteImport } from './routes/app.forum.$courseId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminSupportAssistantRouteImport } from './routes/app.admin.support-assistant'
import { Route as AppAdminSupportRouteImport } from './routes/app.admin.support'
import { Route as AppAdminStatisticsRouteImport } from './routes/app.admin.statistics'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminReportTemplatesRouteImport } from './routes/app.admin.report-templates'
import { Route as AppAdminErrorsRouteImport } from './routes/app.admin.errors'
import { Route as AppAdminEmailSettingsRouteImport } from './routes/app.admin.email-settings'
import { Route as AppAdminCoursesRouteImport } from './routes/app.admin.courses'
import { Route as AppAdminAuditLogsRouteImport } from './routes/app.admin.audit-logs'
import { Route as AppAdminAiPromptsRouteImport } from './routes/app.admin.ai-prompts'
import { Route as AppAdminAiCronRouteImport } from './routes/app.admin.ai-cron'
import { Route as AppAdminAcademicRouteImport } from './routes/app.admin.academic'
import { Route as AppTeacherWhiteboardsIndexRouteImport } from './routes/app.teacher.whiteboards.index'
import { Route as AppTeacherExamsIndexRouteImport } from './routes/app.teacher.exams.index'
import { Route as AppStudentWhiteboardsIndexRouteImport } from './routes/app.student.whiteboards.index'
import { Route as AppStudentTutorIndexRouteImport } from './routes/app.student.tutor.index'
import { Route as AppTeacherWhiteboardsIdRouteImport } from './routes/app.teacher.whiteboards.$id'
import { Route as AppTeacherMonitorExamIdRouteImport } from './routes/app.teacher.monitor.$examId'
import { Route as AppTeacherKahootGameIdRouteImport } from './routes/app.teacher.kahoot.$gameId'
import { Route as AppTeacherGradingCourseIdRouteImport } from './routes/app.teacher.grading.$courseId'
import { Route as AppTeacherExamsExamIdRouteImport } from './routes/app.teacher.exams.$examId'
import { Route as AppTeacherBoardCourseIdRouteImport } from './routes/app.teacher.board.$courseId'
import { Route as AppStudentWorkshopWorkshopIdRouteImport } from './routes/app.student.workshop.$workshopId'
import { Route as AppStudentWhiteboardsIdRouteImport } from './routes/app.student.whiteboards.$id'
import { Route as AppStudentTutorCourseIdRouteImport } from './routes/app.student.tutor.$courseId'
import { Route as AppStudentTakeExamIdRouteImport } from './routes/app.student.take.$examId'
import { Route as AppStudentReviewExamIdRouteImport } from './routes/app.student.review.$examId'
import { Route as AppStudentProjectProjectIdRouteImport } from './routes/app.student.project.$projectId'
import { Route as AppStudentKahootGameIdRouteImport } from './routes/app.student.kahoot.$gameId'
import { Route as AppForumCourseIdForumIdRouteImport } from './routes/app.forum.$courseId.$forumId'
import { Route as AppForumCourseIdForumIdThreadIdRouteImport } from './routes/app.forum.$courseId.$forumId.$threadId'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VerifyShortCodeRoute = VerifyShortCodeRouteImport.update({
  id: '/verify/$shortCode',
  path: '/verify/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoPinRoute = RetoPinRouteImport.update({
  id: '/reto/$pin',
  path: '/reto/$pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailChangeRoute = AuthConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCancelEmailChangeRoute = AuthCancelEmailChangeRouteImport.update({
  id: '/cancel-email-change',
  path: '/cancel-email-change',
  getParentRoute: () => AuthRoute,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherWorkshopsRoute = AppTeacherWorkshopsRouteImport.update({
  id: '/teacher/workshops',
  path: '/teacher/workshops',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherStudentsRoute = AppTeacherStudentsRouteImport.update({
  id: '/teacher/students',
  path: '/teacher/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherStatisticsRoute = AppTeacherStatisticsRouteImport.update({
  id: '/teacher/statistics',
  path: '/teacher/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherReportsRoute = AppTeacherReportsRouteImport.update({
  id: '/teacher/reports',
  path: '/teacher/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherQuestionBankRoute = AppTeacherQuestionBankRouteImport.update({
  id: '/teacher/question-bank',
  path: '/teacher/question-bank',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherProjectsRoute = AppTeacherProjectsRouteImport.update({
  id: '/teacher/projects',
  path: '/teacher/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherPollsRoute = AppTeacherPollsRouteImport.update({
  id: '/teacher/polls',
  path: '/teacher/polls',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherGradebookRoute = AppTeacherGradebookRouteImport.update({
  id: '/teacher/gradebook',
  path: '/teacher/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherCoursesRoute = AppTeacherCoursesRouteImport.update({
  id: '/teacher/courses',
  path: '/teacher/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherContentsRoute = AppTeacherContentsRouteImport.update({
  id: '/teacher/contents',
  path: '/teacher/contents',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherCalendarRoute = AppTeacherCalendarRouteImport.update({
  id: '/teacher/calendar',
  path: '/teacher/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherAuditLogsRoute = AppTeacherAuditLogsRouteImport.update({
  id: '/teacher/audit-logs',
  path: '/teacher/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherAttendanceRoute = AppTeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherAiPromptsRoute = AppTeacherAiPromptsRouteImport.update({
  id: '/teacher/ai-prompts',
  path: '/teacher/ai-prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherAiCronRoute = AppTeacherAiCronRouteImport.update({
  id: '/teacher/ai-cron',
  path: '/teacher/ai-cron',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminTenantsRoute = AppSuperadminTenantsRouteImport.update({
  id: '/superadmin/tenants',
  path: '/superadmin/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminSystemRoute = AppSuperadminSystemRouteImport.update({
  id: '/superadmin/system',
  path: '/superadmin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminSupportRoute = AppSuperadminSupportRouteImport.update({
  id: '/superadmin/support',
  path: '/superadmin/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminPricingCalculatorRoute =
  AppSuperadminPricingCalculatorRouteImport.update({
    id: '/superadmin/pricing-calculator',
    path: '/superadmin/pricing-calculator',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentWorkshopsRoute = AppStudentWorkshopsRouteImport.update({
  id: '/student/workshops',
  path: '/student/workshops',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentProjectsRoute = AppStudentProjectsRouteImport.update({
  id: '/student/projects',
  path: '/student/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentPollsRoute = AppStudentPollsRouteImport.update({
  id: '/student/polls',
  path: '/student/polls',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentGradesRoute = AppStudentGradesRouteImport.update({
  id: '/student/grades',
  path: '/student/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentExamsRoute = AppStudentExamsRouteImport.update({
  id: '/student/exams',
  path: '/student/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentCoursesRoute = AppStudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentCertificatesRoute = AppStudentCertificatesRouteImport.update({
  id: '/student/certificates',
  path: '/student/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentCalendarRoute = AppStudentCalendarRouteImport.update({
  id: '/student/calendar',
  path: '/student/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentAttendanceRoute = AppStudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppForumCourseIdRoute = AppForumCourseIdRouteImport.update({
  id: '/forum/$courseId',
  path: '/forum/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSupportAssistantRoute =
  AppAdminSupportAssistantRouteImport.update({
    id: '/admin/support-assistant',
    path: '/admin/support-assistant',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSupportRoute = AppAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStatisticsRoute = AppAdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportTemplatesRoute = AppAdminReportTemplatesRouteImport.update({
  id: '/admin/report-templates',
  path: '/admin/report-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminErrorsRoute = AppAdminErrorsRouteImport.update({
  id: '/admin/errors',
  path: '/admin/errors',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailSettingsRoute = AppAdminEmailSettingsRouteImport.update({
  id: '/admin/email-settings',
  path: '/admin/email-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCoursesRoute = AppAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAiPromptsRoute = AppAdminAiPromptsRouteImport.update({
  id: '/admin/ai-prompts',
  path: '/admin/ai-prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAiCronRoute = AppAdminAiCronRouteImport.update({
  id: '/admin/ai-cron',
  path: '/admin/ai-cron',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAcademicRoute = AppAdminAcademicRouteImport.update({
  id: '/admin/academic',
  path: '/admin/academic',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherWhiteboardsIndexRoute =
  AppTeacherWhiteboardsIndexRouteImport.update({
    id: '/teacher/whiteboards/',
    path: '/teacher/whiteboards/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTeacherExamsIndexRoute = AppTeacherExamsIndexRouteImport.update({
  id: '/teacher/exams/',
  path: '/teacher/exams/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentWhiteboardsIndexRoute =
  AppStudentWhiteboardsIndexRouteImport.update({
    id: '/student/whiteboards/',
    path: '/student/whiteboards/',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentTutorIndexRoute = AppStudentTutorIndexRouteImport.update({
  id: '/student/tutor/',
  path: '/student/tutor/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherWhiteboardsIdRoute = AppTeacherWhiteboardsIdRouteImport.update({
  id: '/teacher/whiteboards/$id',
  path: '/teacher/whiteboards/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherMonitorExamIdRoute = AppTeacherMonitorExamIdRouteImport.update({
  id: '/teacher/monitor/$examId',
  path: '/teacher/monitor/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherKahootGameIdRoute = AppTeacherKahootGameIdRouteImport.update({
  id: '/teacher/kahoot/$gameId',
  path: '/teacher/kahoot/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherGradingCourseIdRoute =
  AppTeacherGradingCourseIdRouteImport.update({
    id: '/teacher/grading/$courseId',
    path: '/teacher/grading/$courseId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTeacherExamsExamIdRoute = AppTeacherExamsExamIdRouteImport.update({
  id: '/teacher/exams/$examId',
  path: '/teacher/exams/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherBoardCourseIdRoute = AppTeacherBoardCourseIdRouteImport.update({
  id: '/teacher/board/$courseId',
  path: '/teacher/board/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentWorkshopWorkshopIdRoute =
  AppStudentWorkshopWorkshopIdRouteImport.update({
    id: '/student/workshop/$workshopId',
    path: '/student/workshop/$workshopId',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentWhiteboardsIdRoute = AppStudentWhiteboardsIdRouteImport.update({
  id: '/student/whiteboards/$id',
  path: '/student/whiteboards/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentTutorCourseIdRoute = AppStudentTutorCourseIdRouteImport.update({
  id: '/student/tutor/$courseId',
  path: '/student/tutor/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentTakeExamIdRoute = AppStudentTakeExamIdRouteImport.update({
  id: '/student/take/$examId',
  path: '/student/take/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentReviewExamIdRoute = AppStudentReviewExamIdRouteImport.update({
  id: '/student/review/$examId',
  path: '/student/review/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentProjectProjectIdRoute =
  AppStudentProjectProjectIdRouteImport.update({
    id: '/student/project/$projectId',
    path: '/student/project/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentKahootGameIdRoute = AppStudentKahootGameIdRouteImport.update({
  id: '/student/kahoot/$gameId',
  path: '/student/kahoot/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const AppForumCourseIdForumIdRoute = AppForumCourseIdForumIdRouteImport.update({
  id: '/$forumId',
  path: '/$forumId',
  getParentRoute: () => AppForumCourseIdRoute,
} as any)
const AppForumCourseIdForumIdThreadIdRoute =
  AppForumCourseIdForumIdThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AppForumCourseIdForumIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/asistencia': typeof AsistenciaRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/trash': typeof AppTrashRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/videos': typeof AppVideosRoute
  '/auth/cancel-email-change': typeof AuthCancelEmailChangeRoute
  '/auth/confirm-email-change': typeof AuthConfirmEmailChangeRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
  '/reto/$pin': typeof RetoPinRoute
  '/verify/$shortCode': typeof VerifyShortCodeRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/academic': typeof AppAdminAcademicRoute
  '/app/admin/ai-cron': typeof AppAdminAiCronRoute
  '/app/admin/ai-prompts': typeof AppAdminAiPromptsRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/email-settings': typeof AppAdminEmailSettingsRoute
  '/app/admin/errors': typeof AppAdminErrorsRoute
  '/app/admin/report-templates': typeof AppAdminReportTemplatesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/statistics': typeof AppAdminStatisticsRoute
  '/app/admin/support': typeof AppAdminSupportRoute
  '/app/admin/support-assistant': typeof AppAdminSupportAssistantRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/forum/$courseId': typeof AppForumCourseIdRouteWithChildren
  '/app/student/attendance': typeof AppStudentAttendanceRoute
  '/app/student/calendar': typeof AppStudentCalendarRoute
  '/app/student/certificates': typeof AppStudentCertificatesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/exams': typeof AppStudentExamsRoute
  '/app/student/grades': typeof AppStudentGradesRoute
  '/app/student/polls': typeof AppStudentPollsRoute
  '/app/student/projects': typeof AppStudentProjectsRoute
  '/app/student/workshops': typeof AppStudentWorkshopsRoute
  '/app/superadmin/pricing-calculator': typeof AppSuperadminPricingCalculatorRoute
  '/app/superadmin/support': typeof AppSuperadminSupportRoute
  '/app/superadmin/system': typeof AppSuperadminSystemRoute
  '/app/superadmin/tenants': typeof AppSuperadminTenantsRoute
  '/app/teacher/ai-cron': typeof AppTeacherAiCronRoute
  '/app/teacher/ai-prompts': typeof AppTeacherAiPromptsRoute
  '/app/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/app/teacher/audit-logs': typeof AppTeacherAuditLogsRoute
  '/app/teacher/calendar': typeof AppTeacherCalendarRoute
  '/app/teacher/contents': typeof AppTeacherContentsRoute
  '/app/teacher/courses': typeof AppTeacherCoursesRoute
  '/app/teacher/gradebook': typeof AppTeacherGradebookRoute
  '/app/teacher/polls': typeof AppTeacherPollsRoute
  '/app/teacher/projects': typeof AppTeacherProjectsRoute
  '/app/teacher/question-bank': typeof AppTeacherQuestionBankRoute
  '/app/teacher/reports': typeof AppTeacherReportsRoute
  '/app/teacher/statistics': typeof AppTeacherStatisticsRoute
  '/app/teacher/students': typeof AppTeacherStudentsRoute
  '/app/teacher/workshops': typeof AppTeacherWorkshopsRoute
  '/app/forum/$courseId/$forumId': typeof AppForumCourseIdForumIdRouteWithChildren
  '/app/student/kahoot/$gameId': typeof AppStudentKahootGameIdRoute
  '/app/student/project/$projectId': typeof AppStudentProjectProjectIdRoute
  '/app/student/review/$examId': typeof AppStudentReviewExamIdRoute
  '/app/student/take/$examId': typeof AppStudentTakeExamIdRoute
  '/app/student/tutor/$courseId': typeof AppStudentTutorCourseIdRoute
  '/app/student/whiteboards/$id': typeof AppStudentWhiteboardsIdRoute
  '/app/student/workshop/$workshopId': typeof AppStudentWorkshopWorkshopIdRoute
  '/app/teacher/board/$courseId': typeof AppTeacherBoardCourseIdRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/grading/$courseId': typeof AppTeacherGradingCourseIdRoute
  '/app/teacher/kahoot/$gameId': typeof AppTeacherKahootGameIdRoute
  '/app/teacher/monitor/$examId': typeof AppTeacherMonitorExamIdRoute
  '/app/teacher/whiteboards/$id': typeof AppTeacherWhiteboardsIdRoute
  '/app/student/tutor/': typeof AppStudentTutorIndexRoute
  '/app/student/whiteboards/': typeof AppStudentWhiteboardsIndexRoute
  '/app/teacher/exams/': typeof AppTeacherExamsIndexRoute
  '/app/teacher/whiteboards/': typeof AppTeacherWhiteboardsIndexRoute
  '/app/forum/$courseId/$forumId/$threadId': typeof AppForumCourseIdForumIdThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/privacy': typeof PrivacyRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/trash': typeof AppTrashRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/videos': typeof AppVideosRoute
  '/auth/cancel-email-change': typeof AuthCancelEmailChangeRoute
  '/auth/confirm-email-change': typeof AuthConfirmEmailChangeRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
  '/reto/$pin': typeof RetoPinRoute
  '/verify/$shortCode': typeof VerifyShortCodeRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/app/admin/academic': typeof AppAdminAcademicRoute
  '/app/admin/ai-cron': typeof AppAdminAiCronRoute
  '/app/admin/ai-prompts': typeof AppAdminAiPromptsRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/email-settings': typeof AppAdminEmailSettingsRoute
  '/app/admin/errors': typeof AppAdminErrorsRoute
  '/app/admin/report-templates': typeof AppAdminReportTemplatesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/statistics': typeof AppAdminStatisticsRoute
  '/app/admin/support': typeof AppAdminSupportRoute
  '/app/admin/support-assistant': typeof AppAdminSupportAssistantRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/forum/$courseId': typeof AppForumCourseIdRouteWithChildren
  '/app/student/attendance': typeof AppStudentAttendanceRoute
  '/app/student/calendar': typeof AppStudentCalendarRoute
  '/app/student/certificates': typeof AppStudentCertificatesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/exams': typeof AppStudentExamsRoute
  '/app/student/grades': typeof AppStudentGradesRoute
  '/app/student/polls': typeof AppStudentPollsRoute
  '/app/student/projects': typeof AppStudentProjectsRoute
  '/app/student/workshops': typeof AppStudentWorkshopsRoute
  '/app/superadmin/pricing-calculator': typeof AppSuperadminPricingCalculatorRoute
  '/app/superadmin/support': typeof AppSuperadminSupportRoute
  '/app/superadmin/system': typeof AppSuperadminSystemRoute
  '/app/superadmin/tenants': typeof AppSuperadminTenantsRoute
  '/app/teacher/ai-cron': typeof AppTeacherAiCronRoute
  '/app/teacher/ai-prompts': typeof AppTeacherAiPromptsRoute
  '/app/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/app/teacher/audit-logs': typeof AppTeacherAuditLogsRoute
  '/app/teacher/calendar': typeof AppTeacherCalendarRoute
  '/app/teacher/contents': typeof AppTeacherContentsRoute
  '/app/teacher/courses': typeof AppTeacherCoursesRoute
  '/app/teacher/gradebook': typeof AppTeacherGradebookRoute
  '/app/teacher/polls': typeof AppTeacherPollsRoute
  '/app/teacher/projects': typeof AppTeacherProjectsRoute
  '/app/teacher/question-bank': typeof AppTeacherQuestionBankRoute
  '/app/teacher/reports': typeof AppTeacherReportsRoute
  '/app/teacher/statistics': typeof AppTeacherStatisticsRoute
  '/app/teacher/students': typeof AppTeacherStudentsRoute
  '/app/teacher/workshops': typeof AppTeacherWorkshopsRoute
  '/app/forum/$courseId/$forumId': typeof AppForumCourseIdForumIdRouteWithChildren
  '/app/student/kahoot/$gameId': typeof AppStudentKahootGameIdRoute
  '/app/student/project/$projectId': typeof AppStudentProjectProjectIdRoute
  '/app/student/review/$examId': typeof AppStudentReviewExamIdRoute
  '/app/student/take/$examId': typeof AppStudentTakeExamIdRoute
  '/app/student/tutor/$courseId': typeof AppStudentTutorCourseIdRoute
  '/app/student/whiteboards/$id': typeof AppStudentWhiteboardsIdRoute
  '/app/student/workshop/$workshopId': typeof AppStudentWorkshopWorkshopIdRoute
  '/app/teacher/board/$courseId': typeof AppTeacherBoardCourseIdRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/grading/$courseId': typeof AppTeacherGradingCourseIdRoute
  '/app/teacher/kahoot/$gameId': typeof AppTeacherKahootGameIdRoute
  '/app/teacher/monitor/$examId': typeof AppTeacherMonitorExamIdRoute
  '/app/teacher/whiteboards/$id': typeof AppTeacherWhiteboardsIdRoute
  '/app/student/tutor': typeof AppStudentTutorIndexRoute
  '/app/student/whiteboards': typeof AppStudentWhiteboardsIndexRoute
  '/app/teacher/exams': typeof AppTeacherExamsIndexRoute
  '/app/teacher/whiteboards': typeof AppTeacherWhiteboardsIndexRoute
  '/app/forum/$courseId/$forumId/$threadId': typeof AppForumCourseIdForumIdThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/asistencia': typeof AsistenciaRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/trash': typeof AppTrashRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/videos': typeof AppVideosRoute
  '/auth/cancel-email-change': typeof AuthCancelEmailChangeRoute
  '/auth/confirm-email-change': typeof AuthConfirmEmailChangeRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
  '/reto/$pin': typeof RetoPinRoute
  '/verify/$shortCode': typeof VerifyShortCodeRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/academic': typeof AppAdminAcademicRoute
  '/app/admin/ai-cron': typeof AppAdminAiCronRoute
  '/app/admin/ai-prompts': typeof AppAdminAiPromptsRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/email-settings': typeof AppAdminEmailSettingsRoute
  '/app/admin/errors': typeof AppAdminErrorsRoute
  '/app/admin/report-templates': typeof AppAdminReportTemplatesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/statistics': typeof AppAdminStatisticsRoute
  '/app/admin/support': typeof AppAdminSupportRoute
  '/app/admin/support-assistant': typeof AppAdminSupportAssistantRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/forum/$courseId': typeof AppForumCourseIdRouteWithChildren
  '/app/student/attendance': typeof AppStudentAttendanceRoute
  '/app/student/calendar': typeof AppStudentCalendarRoute
  '/app/student/certificates': typeof AppStudentCertificatesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/exams': typeof AppStudentExamsRoute
  '/app/student/grades': typeof AppStudentGradesRoute
  '/app/student/polls': typeof AppStudentPollsRoute
  '/app/student/projects': typeof AppStudentProjectsRoute
  '/app/student/workshops': typeof AppStudentWorkshopsRoute
  '/app/superadmin/pricing-calculator': typeof AppSuperadminPricingCalculatorRoute
  '/app/superadmin/support': typeof AppSuperadminSupportRoute
  '/app/superadmin/system': typeof AppSuperadminSystemRoute
  '/app/superadmin/tenants': typeof AppSuperadminTenantsRoute
  '/app/teacher/ai-cron': typeof AppTeacherAiCronRoute
  '/app/teacher/ai-prompts': typeof AppTeacherAiPromptsRoute
  '/app/teacher/attendance': typeof AppTeacherAttendanceRoute
  '/app/teacher/audit-logs': typeof AppTeacherAuditLogsRoute
  '/app/teacher/calendar': typeof AppTeacherCalendarRoute
  '/app/teacher/contents': typeof AppTeacherContentsRoute
  '/app/teacher/courses': typeof AppTeacherCoursesRoute
  '/app/teacher/gradebook': typeof AppTeacherGradebookRoute
  '/app/teacher/polls': typeof AppTeacherPollsRoute
  '/app/teacher/projects': typeof AppTeacherProjectsRoute
  '/app/teacher/question-bank': typeof AppTeacherQuestionBankRoute
  '/app/teacher/reports': typeof AppTeacherReportsRoute
  '/app/teacher/statistics': typeof AppTeacherStatisticsRoute
  '/app/teacher/students': typeof AppTeacherStudentsRoute
  '/app/teacher/workshops': typeof AppTeacherWorkshopsRoute
  '/app/forum/$courseId/$forumId': typeof AppForumCourseIdForumIdRouteWithChildren
  '/app/student/kahoot/$gameId': typeof AppStudentKahootGameIdRoute
  '/app/student/project/$projectId': typeof AppStudentProjectProjectIdRoute
  '/app/student/review/$examId': typeof AppStudentReviewExamIdRoute
  '/app/student/take/$examId': typeof AppStudentTakeExamIdRoute
  '/app/student/tutor/$courseId': typeof AppStudentTutorCourseIdRoute
  '/app/student/whiteboards/$id': typeof AppStudentWhiteboardsIdRoute
  '/app/student/workshop/$workshopId': typeof AppStudentWorkshopWorkshopIdRoute
  '/app/teacher/board/$courseId': typeof AppTeacherBoardCourseIdRoute
  '/app/teacher/exams/$examId': typeof AppTeacherExamsExamIdRoute
  '/app/teacher/grading/$courseId': typeof AppTeacherGradingCourseIdRoute
  '/app/teacher/kahoot/$gameId': typeof AppTeacherKahootGameIdRoute
  '/app/teacher/monitor/$examId': typeof AppTeacherMonitorExamIdRoute
  '/app/teacher/whiteboards/$id': typeof AppTeacherWhiteboardsIdRoute
  '/app/student/tutor/': typeof AppStudentTutorIndexRoute
  '/app/student/whiteboards/': typeof AppStudentWhiteboardsIndexRoute
  '/app/teacher/exams/': typeof AppTeacherExamsIndexRoute
  '/app/teacher/whiteboards/': typeof AppTeacherWhiteboardsIndexRoute
  '/app/forum/$courseId/$forumId/$threadId': typeof AppForumCourseIdForumIdThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/asistencia'
    | '/auth'
    | '/privacy'
    | '/app/assistant'
    | '/app/certificates'
    | '/app/messages'
    | '/app/preferences'
    | '/app/privacy'
    | '/app/trash'
    | '/app/unauthorized'
    | '/app/videos'
    | '/auth/cancel-email-change'
    | '/auth/confirm-email-change'
    | '/auth/reset-password'
    | '/auth/sso-callback'
    | '/reto/$pin'
    | '/verify/$shortCode'
    | '/app/'
    | '/auth/'
    | '/app/admin/academic'
    | '/app/admin/ai-cron'
    | '/app/admin/ai-prompts'
    | '/app/admin/audit-logs'
    | '/app/admin/courses'
    | '/app/admin/email-settings'
    | '/app/admin/errors'
    | '/app/admin/report-templates'
    | '/app/admin/settings'
    | '/app/admin/statistics'
    | '/app/admin/support'
    | '/app/admin/support-assistant'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/forum/$courseId'
    | '/app/student/attendance'
    | '/app/student/calendar'
    | '/app/student/certificates'
    | '/app/student/courses'
    | '/app/student/exams'
    | '/app/student/grades'
    | '/app/student/polls'
    | '/app/student/projects'
    | '/app/student/workshops'
    | '/app/superadmin/pricing-calculator'
    | '/app/superadmin/support'
    | '/app/superadmin/system'
    | '/app/superadmin/tenants'
    | '/app/teacher/ai-cron'
    | '/app/teacher/ai-prompts'
    | '/app/teacher/attendance'
    | '/app/teacher/audit-logs'
    | '/app/teacher/calendar'
    | '/app/teacher/contents'
    | '/app/teacher/courses'
    | '/app/teacher/gradebook'
    | '/app/teacher/polls'
    | '/app/teacher/projects'
    | '/app/teacher/question-bank'
    | '/app/teacher/reports'
    | '/app/teacher/statistics'
    | '/app/teacher/students'
    | '/app/teacher/workshops'
    | '/app/forum/$courseId/$forumId'
    | '/app/student/kahoot/$gameId'
    | '/app/student/project/$projectId'
    | '/app/student/review/$examId'
    | '/app/student/take/$examId'
    | '/app/student/tutor/$courseId'
    | '/app/student/whiteboards/$id'
    | '/app/student/workshop/$workshopId'
    | '/app/teacher/board/$courseId'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/grading/$courseId'
    | '/app/teacher/kahoot/$gameId'
    | '/app/teacher/monitor/$examId'
    | '/app/teacher/whiteboards/$id'
    | '/app/student/tutor/'
    | '/app/student/whiteboards/'
    | '/app/teacher/exams/'
    | '/app/teacher/whiteboards/'
    | '/app/forum/$courseId/$forumId/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistencia'
    | '/privacy'
    | '/app/assistant'
    | '/app/certificates'
    | '/app/messages'
    | '/app/preferences'
    | '/app/privacy'
    | '/app/trash'
    | '/app/unauthorized'
    | '/app/videos'
    | '/auth/cancel-email-change'
    | '/auth/confirm-email-change'
    | '/auth/reset-password'
    | '/auth/sso-callback'
    | '/reto/$pin'
    | '/verify/$shortCode'
    | '/app'
    | '/auth'
    | '/app/admin/academic'
    | '/app/admin/ai-cron'
    | '/app/admin/ai-prompts'
    | '/app/admin/audit-logs'
    | '/app/admin/courses'
    | '/app/admin/email-settings'
    | '/app/admin/errors'
    | '/app/admin/report-templates'
    | '/app/admin/settings'
    | '/app/admin/statistics'
    | '/app/admin/support'
    | '/app/admin/support-assistant'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/forum/$courseId'
    | '/app/student/attendance'
    | '/app/student/calendar'
    | '/app/student/certificates'
    | '/app/student/courses'
    | '/app/student/exams'
    | '/app/student/grades'
    | '/app/student/polls'
    | '/app/student/projects'
    | '/app/student/workshops'
    | '/app/superadmin/pricing-calculator'
    | '/app/superadmin/support'
    | '/app/superadmin/system'
    | '/app/superadmin/tenants'
    | '/app/teacher/ai-cron'
    | '/app/teacher/ai-prompts'
    | '/app/teacher/attendance'
    | '/app/teacher/audit-logs'
    | '/app/teacher/calendar'
    | '/app/teacher/contents'
    | '/app/teacher/courses'
    | '/app/teacher/gradebook'
    | '/app/teacher/polls'
    | '/app/teacher/projects'
    | '/app/teacher/question-bank'
    | '/app/teacher/reports'
    | '/app/teacher/statistics'
    | '/app/teacher/students'
    | '/app/teacher/workshops'
    | '/app/forum/$courseId/$forumId'
    | '/app/student/kahoot/$gameId'
    | '/app/student/project/$projectId'
    | '/app/student/review/$examId'
    | '/app/student/take/$examId'
    | '/app/student/tutor/$courseId'
    | '/app/student/whiteboards/$id'
    | '/app/student/workshop/$workshopId'
    | '/app/teacher/board/$courseId'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/grading/$courseId'
    | '/app/teacher/kahoot/$gameId'
    | '/app/teacher/monitor/$examId'
    | '/app/teacher/whiteboards/$id'
    | '/app/student/tutor'
    | '/app/student/whiteboards'
    | '/app/teacher/exams'
    | '/app/teacher/whiteboards'
    | '/app/forum/$courseId/$forumId/$threadId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/asistencia'
    | '/auth'
    | '/privacy'
    | '/app/assistant'
    | '/app/certificates'
    | '/app/messages'
    | '/app/preferences'
    | '/app/privacy'
    | '/app/trash'
    | '/app/unauthorized'
    | '/app/videos'
    | '/auth/cancel-email-change'
    | '/auth/confirm-email-change'
    | '/auth/reset-password'
    | '/auth/sso-callback'
    | '/reto/$pin'
    | '/verify/$shortCode'
    | '/app/'
    | '/auth/'
    | '/app/admin/academic'
    | '/app/admin/ai-cron'
    | '/app/admin/ai-prompts'
    | '/app/admin/audit-logs'
    | '/app/admin/courses'
    | '/app/admin/email-settings'
    | '/app/admin/errors'
    | '/app/admin/report-templates'
    | '/app/admin/settings'
    | '/app/admin/statistics'
    | '/app/admin/support'
    | '/app/admin/support-assistant'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/forum/$courseId'
    | '/app/student/attendance'
    | '/app/student/calendar'
    | '/app/student/certificates'
    | '/app/student/courses'
    | '/app/student/exams'
    | '/app/student/grades'
    | '/app/student/polls'
    | '/app/student/projects'
    | '/app/student/workshops'
    | '/app/superadmin/pricing-calculator'
    | '/app/superadmin/support'
    | '/app/superadmin/system'
    | '/app/superadmin/tenants'
    | '/app/teacher/ai-cron'
    | '/app/teacher/ai-prompts'
    | '/app/teacher/attendance'
    | '/app/teacher/audit-logs'
    | '/app/teacher/calendar'
    | '/app/teacher/contents'
    | '/app/teacher/courses'
    | '/app/teacher/gradebook'
    | '/app/teacher/polls'
    | '/app/teacher/projects'
    | '/app/teacher/question-bank'
    | '/app/teacher/reports'
    | '/app/teacher/statistics'
    | '/app/teacher/students'
    | '/app/teacher/workshops'
    | '/app/forum/$courseId/$forumId'
    | '/app/student/kahoot/$gameId'
    | '/app/student/project/$projectId'
    | '/app/student/review/$examId'
    | '/app/student/take/$examId'
    | '/app/student/tutor/$courseId'
    | '/app/student/whiteboards/$id'
    | '/app/student/workshop/$workshopId'
    | '/app/teacher/board/$courseId'
    | '/app/teacher/exams/$examId'
    | '/app/teacher/grading/$courseId'
    | '/app/teacher/kahoot/$gameId'
    | '/app/teacher/monitor/$examId'
    | '/app/teacher/whiteboards/$id'
    | '/app/student/tutor/'
    | '/app/student/whiteboards/'
    | '/app/teacher/exams/'
    | '/app/teacher/whiteboards/'
    | '/app/forum/$courseId/$forumId/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AsistenciaRoute: typeof AsistenciaRoute
  AuthRoute: typeof AuthRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RetoPinRoute: typeof RetoPinRoute
  VerifyShortCodeRoute: typeof VerifyShortCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/$shortCode': {
      id: '/verify/$shortCode'
      path: '/verify/$shortCode'
      fullPath: '/verify/$shortCode'
      preLoaderRoute: typeof VerifyShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto/$pin': {
      id: '/reto/$pin'
      path: '/reto/$pin'
      fullPath: '/reto/$pin'
      preLoaderRoute: typeof RetoPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-callback': {
      id: '/auth/sso-callback'
      path: '/sso-callback'
      fullPath: '/auth/sso-callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email-change': {
      id: '/auth/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/auth/confirm-email-change'
      preLoaderRoute: typeof AuthConfirmEmailChangeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/cancel-email-change': {
      id: '/auth/cancel-email-change'
      path: '/cancel-email-change'
      fullPath: '/auth/cancel-email-change'
      preLoaderRoute: typeof AuthCancelEmailChangeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/videos': {
      id: '/app/videos'
      path: '/videos'
      fullPath: '/app/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unauthorized': {
      id: '/app/unauthorized'
      path: '/unauthorized'
      fullPath: '/app/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trash': {
      id: '/app/trash'
      path: '/trash'
      fullPath: '/app/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacy': {
      id: '/app/privacy'
      path: '/privacy'
      fullPath: '/app/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preferences': {
      id: '/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/workshops': {
      id: '/app/teacher/workshops'
      path: '/teacher/workshops'
      fullPath: '/app/teacher/workshops'
      preLoaderRoute: typeof AppTeacherWorkshopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/students': {
      id: '/app/teacher/students'
      path: '/teacher/students'
      fullPath: '/app/teacher/students'
      preLoaderRoute: typeof AppTeacherStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/statistics': {
      id: '/app/teacher/statistics'
      path: '/teacher/statistics'
      fullPath: '/app/teacher/statistics'
      preLoaderRoute: typeof AppTeacherStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/reports': {
      id: '/app/teacher/reports'
      path: '/teacher/reports'
      fullPath: '/app/teacher/reports'
      preLoaderRoute: typeof AppTeacherReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/question-bank': {
      id: '/app/teacher/question-bank'
      path: '/teacher/question-bank'
      fullPath: '/app/teacher/question-bank'
      preLoaderRoute: typeof AppTeacherQuestionBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/projects': {
      id: '/app/teacher/projects'
      path: '/teacher/projects'
      fullPath: '/app/teacher/projects'
      preLoaderRoute: typeof AppTeacherProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/polls': {
      id: '/app/teacher/polls'
      path: '/teacher/polls'
      fullPath: '/app/teacher/polls'
      preLoaderRoute: typeof AppTeacherPollsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/gradebook': {
      id: '/app/teacher/gradebook'
      path: '/teacher/gradebook'
      fullPath: '/app/teacher/gradebook'
      preLoaderRoute: typeof AppTeacherGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/courses': {
      id: '/app/teacher/courses'
      path: '/teacher/courses'
      fullPath: '/app/teacher/courses'
      preLoaderRoute: typeof AppTeacherCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/contents': {
      id: '/app/teacher/contents'
      path: '/teacher/contents'
      fullPath: '/app/teacher/contents'
      preLoaderRoute: typeof AppTeacherContentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/calendar': {
      id: '/app/teacher/calendar'
      path: '/teacher/calendar'
      fullPath: '/app/teacher/calendar'
      preLoaderRoute: typeof AppTeacherCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/audit-logs': {
      id: '/app/teacher/audit-logs'
      path: '/teacher/audit-logs'
      fullPath: '/app/teacher/audit-logs'
      preLoaderRoute: typeof AppTeacherAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/attendance': {
      id: '/app/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/app/teacher/attendance'
      preLoaderRoute: typeof AppTeacherAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/ai-prompts': {
      id: '/app/teacher/ai-prompts'
      path: '/teacher/ai-prompts'
      fullPath: '/app/teacher/ai-prompts'
      preLoaderRoute: typeof AppTeacherAiPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/ai-cron': {
      id: '/app/teacher/ai-cron'
      path: '/teacher/ai-cron'
      fullPath: '/app/teacher/ai-cron'
      preLoaderRoute: typeof AppTeacherAiCronRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/superadmin/tenants': {
      id: '/app/superadmin/tenants'
      path: '/superadmin/tenants'
      fullPath: '/app/superadmin/tenants'
      preLoaderRoute: typeof AppSuperadminTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/superadmin/system': {
      id: '/app/superadmin/system'
      path: '/superadmin/system'
      fullPath: '/app/superadmin/system'
      preLoaderRoute: typeof AppSuperadminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/superadmin/support': {
      id: '/app/superadmin/support'
      path: '/superadmin/support'
      fullPath: '/app/superadmin/support'
      preLoaderRoute: typeof AppSuperadminSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/superadmin/pricing-calculator': {
      id: '/app/superadmin/pricing-calculator'
      path: '/superadmin/pricing-calculator'
      fullPath: '/app/superadmin/pricing-calculator'
      preLoaderRoute: typeof AppSuperadminPricingCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/workshops': {
      id: '/app/student/workshops'
      path: '/student/workshops'
      fullPath: '/app/student/workshops'
      preLoaderRoute: typeof AppStudentWorkshopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/projects': {
      id: '/app/student/projects'
      path: '/student/projects'
      fullPath: '/app/student/projects'
      preLoaderRoute: typeof AppStudentProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/polls': {
      id: '/app/student/polls'
      path: '/student/polls'
      fullPath: '/app/student/polls'
      preLoaderRoute: typeof AppStudentPollsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/grades': {
      id: '/app/student/grades'
      path: '/student/grades'
      fullPath: '/app/student/grades'
      preLoaderRoute: typeof AppStudentGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/exams': {
      id: '/app/student/exams'
      path: '/student/exams'
      fullPath: '/app/student/exams'
      preLoaderRoute: typeof AppStudentExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/courses': {
      id: '/app/student/courses'
      path: '/student/courses'
      fullPath: '/app/student/courses'
      preLoaderRoute: typeof AppStudentCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/certificates': {
      id: '/app/student/certificates'
      path: '/student/certificates'
      fullPath: '/app/student/certificates'
      preLoaderRoute: typeof AppStudentCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/calendar': {
      id: '/app/student/calendar'
      path: '/student/calendar'
      fullPath: '/app/student/calendar'
      preLoaderRoute: typeof AppStudentCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/attendance': {
      id: '/app/student/attendance'
      path: '/student/attendance'
      fullPath: '/app/student/attendance'
      preLoaderRoute: typeof AppStudentAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forum/$courseId': {
      id: '/app/forum/$courseId'
      path: '/forum/$courseId'
      fullPath: '/app/forum/$courseId'
      preLoaderRoute: typeof AppForumCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/admin/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/support-assistant': {
      id: '/app/admin/support-assistant'
      path: '/admin/support-assistant'
      fullPath: '/app/admin/support-assistant'
      preLoaderRoute: typeof AppAdminSupportAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/support': {
      id: '/app/admin/support'
      path: '/admin/support'
      fullPath: '/app/admin/support'
      preLoaderRoute: typeof AppAdminSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/statistics': {
      id: '/app/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/app/admin/statistics'
      preLoaderRoute: typeof AppAdminStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/report-templates': {
      id: '/app/admin/report-templates'
      path: '/admin/report-templates'
      fullPath: '/app/admin/report-templates'
      preLoaderRoute: typeof AppAdminReportTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/errors': {
      id: '/app/admin/errors'
      path: '/admin/errors'
      fullPath: '/app/admin/errors'
      preLoaderRoute: typeof AppAdminErrorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/email-settings': {
      id: '/app/admin/email-settings'
      path: '/admin/email-settings'
      fullPath: '/app/admin/email-settings'
      preLoaderRoute: typeof AppAdminEmailSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/courses': {
      id: '/app/admin/courses'
      path: '/admin/courses'
      fullPath: '/app/admin/courses'
      preLoaderRoute: typeof AppAdminCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit-logs': {
      id: '/app/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/app/admin/audit-logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ai-prompts': {
      id: '/app/admin/ai-prompts'
      path: '/admin/ai-prompts'
      fullPath: '/app/admin/ai-prompts'
      preLoaderRoute: typeof AppAdminAiPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ai-cron': {
      id: '/app/admin/ai-cron'
      path: '/admin/ai-cron'
      fullPath: '/app/admin/ai-cron'
      preLoaderRoute: typeof AppAdminAiCronRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/academic': {
      id: '/app/admin/academic'
      path: '/admin/academic'
      fullPath: '/app/admin/academic'
      preLoaderRoute: typeof AppAdminAcademicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/whiteboards/': {
      id: '/app/teacher/whiteboards/'
      path: '/teacher/whiteboards'
      fullPath: '/app/teacher/whiteboards/'
      preLoaderRoute: typeof AppTeacherWhiteboardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/exams/': {
      id: '/app/teacher/exams/'
      path: '/teacher/exams'
      fullPath: '/app/teacher/exams/'
      preLoaderRoute: typeof AppTeacherExamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/whiteboards/': {
      id: '/app/student/whiteboards/'
      path: '/student/whiteboards'
      fullPath: '/app/student/whiteboards/'
      preLoaderRoute: typeof AppStudentWhiteboardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/tutor/': {
      id: '/app/student/tutor/'
      path: '/student/tutor'
      fullPath: '/app/student/tutor/'
      preLoaderRoute: typeof AppStudentTutorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/whiteboards/$id': {
      id: '/app/teacher/whiteboards/$id'
      path: '/teacher/whiteboards/$id'
      fullPath: '/app/teacher/whiteboards/$id'
      preLoaderRoute: typeof AppTeacherWhiteboardsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/monitor/$examId': {
      id: '/app/teacher/monitor/$examId'
      path: '/teacher/monitor/$examId'
      fullPath: '/app/teacher/monitor/$examId'
      preLoaderRoute: typeof AppTeacherMonitorExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/kahoot/$gameId': {
      id: '/app/teacher/kahoot/$gameId'
      path: '/teacher/kahoot/$gameId'
      fullPath: '/app/teacher/kahoot/$gameId'
      preLoaderRoute: typeof AppTeacherKahootGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/grading/$courseId': {
      id: '/app/teacher/grading/$courseId'
      path: '/teacher/grading/$courseId'
      fullPath: '/app/teacher/grading/$courseId'
      preLoaderRoute: typeof AppTeacherGradingCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/exams/$examId': {
      id: '/app/teacher/exams/$examId'
      path: '/teacher/exams/$examId'
      fullPath: '/app/teacher/exams/$examId'
      preLoaderRoute: typeof AppTeacherExamsExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher/board/$courseId': {
      id: '/app/teacher/board/$courseId'
      path: '/teacher/board/$courseId'
      fullPath: '/app/teacher/board/$courseId'
      preLoaderRoute: typeof AppTeacherBoardCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/workshop/$workshopId': {
      id: '/app/student/workshop/$workshopId'
      path: '/student/workshop/$workshopId'
      fullPath: '/app/student/workshop/$workshopId'
      preLoaderRoute: typeof AppStudentWorkshopWorkshopIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/whiteboards/$id': {
      id: '/app/student/whiteboards/$id'
      path: '/student/whiteboards/$id'
      fullPath: '/app/student/whiteboards/$id'
      preLoaderRoute: typeof AppStudentWhiteboardsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/tutor/$courseId': {
      id: '/app/student/tutor/$courseId'
      path: '/student/tutor/$courseId'
      fullPath: '/app/student/tutor/$courseId'
      preLoaderRoute: typeof AppStudentTutorCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/take/$examId': {
      id: '/app/student/take/$examId'
      path: '/student/take/$examId'
      fullPath: '/app/student/take/$examId'
      preLoaderRoute: typeof AppStudentTakeExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/review/$examId': {
      id: '/app/student/review/$examId'
      path: '/student/review/$examId'
      fullPath: '/app/student/review/$examId'
      preLoaderRoute: typeof AppStudentReviewExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/project/$projectId': {
      id: '/app/student/project/$projectId'
      path: '/student/project/$projectId'
      fullPath: '/app/student/project/$projectId'
      preLoaderRoute: typeof AppStudentProjectProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/kahoot/$gameId': {
      id: '/app/student/kahoot/$gameId'
      path: '/student/kahoot/$gameId'
      fullPath: '/app/student/kahoot/$gameId'
      preLoaderRoute: typeof AppStudentKahootGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forum/$courseId/$forumId': {
      id: '/app/forum/$courseId/$forumId'
      path: '/$forumId'
      fullPath: '/app/forum/$courseId/$forumId'
      preLoaderRoute: typeof AppForumCourseIdForumIdRouteImport
      parentRoute: typeof AppForumCourseIdRoute
    }
    '/app/forum/$courseId/$forumId/$threadId': {
      id: '/app/forum/$courseId/$forumId/$threadId'
      path: '/$threadId'
      fullPath: '/app/forum/$courseId/$forumId/$threadId'
      preLoaderRoute: typeof AppForumCourseIdForumIdThreadIdRouteImport
      parentRoute: typeof AppForumCourseIdForumIdRoute
    }
  }
}

interface AppForumCourseIdForumIdRouteChildren {
  AppForumCourseIdForumIdThreadIdRoute: typeof AppForumCourseIdForumIdThreadIdRoute
}

const AppForumCourseIdForumIdRouteChildren: AppForumCourseIdForumIdRouteChildren =
  {
    AppForumCourseIdForumIdThreadIdRoute: AppForumCourseIdForumIdThreadIdRoute,
  }

const AppForumCourseIdForumIdRouteWithChildren =
  AppForumCourseIdForumIdRoute._addFileChildren(
    AppForumCourseIdForumIdRouteChildren,
  )

interface AppForumCourseIdRouteChildren {
  AppForumCourseIdForumIdRoute: typeof AppForumCourseIdForumIdRouteWithChildren
}

const AppForumCourseIdRouteChildren: AppForumCourseIdRouteChildren = {
  AppForumCourseIdForumIdRoute: AppForumCourseIdForumIdRouteWithChildren,
}

const AppForumCourseIdRouteWithChildren =
  AppForumCourseIdRoute._addFileChildren(AppForumCourseIdRouteChildren)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppTrashRoute: typeof AppTrashRoute
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
  AppVideosRoute: typeof AppVideosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAcademicRoute: typeof AppAdminAcademicRoute
  AppAdminAiCronRoute: typeof AppAdminAiCronRoute
  AppAdminAiPromptsRoute: typeof AppAdminAiPromptsRoute
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminCoursesRoute: typeof AppAdminCoursesRoute
  AppAdminEmailSettingsRoute: typeof AppAdminEmailSettingsRoute
  AppAdminErrorsRoute: typeof AppAdminErrorsRoute
  AppAdminReportTemplatesRoute: typeof AppAdminReportTemplatesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminStatisticsRoute: typeof AppAdminStatisticsRoute
  AppAdminSupportRoute: typeof AppAdminSupportRoute
  AppAdminSupportAssistantRoute: typeof AppAdminSupportAssistantRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppForumCourseIdRoute: typeof AppForumCourseIdRouteWithChildren
  AppStudentAttendanceRoute: typeof AppStudentAttendanceRoute
  AppStudentCalendarRoute: typeof AppStudentCalendarRoute
  AppStudentCertificatesRoute: typeof AppStudentCertificatesRoute
  AppStudentCoursesRoute: typeof AppStudentCoursesRoute
  AppStudentExamsRoute: typeof AppStudentExamsRoute
  AppStudentGradesRoute: typeof AppStudentGradesRoute
  AppStudentPollsRoute: typeof AppStudentPollsRoute
  AppStudentProjectsRoute: typeof AppStudentProjectsRoute
  AppStudentWorkshopsRoute: typeof AppStudentWorkshopsRoute
  AppSuperadminPricingCalculatorRoute: typeof AppSuperadminPricingCalculatorRoute
  AppSuperadminSupportRoute: typeof AppSuperadminSupportRoute
  AppSuperadminSystemRoute: typeof AppSuperadminSystemRoute
  AppSuperadminTenantsRoute: typeof AppSuperadminTenantsRoute
  AppTeacherAiCronRoute: typeof AppTeacherAiCronRoute
  AppTeacherAiPromptsRoute: typeof AppTeacherAiPromptsRoute
  AppTeacherAttendanceRoute: typeof AppTeacherAttendanceRoute
  AppTeacherAuditLogsRoute: typeof AppTeacherAuditLogsRoute
  AppTeacherCalendarRoute: typeof AppTeacherCalendarRoute
  AppTeacherContentsRoute: typeof AppTeacherContentsRoute
  AppTeacherCoursesRoute: typeof AppTeacherCoursesRoute
  AppTeacherGradebookRoute: typeof AppTeacherGradebookRoute
  AppTeacherPollsRoute: typeof AppTeacherPollsRoute
  AppTeacherProjectsRoute: typeof AppTeacherProjectsRoute
  AppTeacherQuestionBankRoute: typeof AppTeacherQuestionBankRoute
  AppTeacherReportsRoute: typeof AppTeacherReportsRoute
  AppTeacherStatisticsRoute: typeof AppTeacherStatisticsRoute
  AppTeacherStudentsRoute: typeof AppTeacherStudentsRoute
  AppTeacherWorkshopsRoute: typeof AppTeacherWorkshopsRoute
  AppStudentKahootGameIdRoute: typeof AppStudentKahootGameIdRoute
  AppStudentProjectProjectIdRoute: typeof AppStudentProjectProjectIdRoute
  AppStudentReviewExamIdRoute: typeof AppStudentReviewExamIdRoute
  AppStudentTakeExamIdRoute: typeof AppStudentTakeExamIdRoute
  AppStudentTutorCourseIdRoute: typeof AppStudentTutorCourseIdRoute
  AppStudentWhiteboardsIdRoute: typeof AppStudentWhiteboardsIdRoute
  AppStudentWorkshopWorkshopIdRoute: typeof AppStudentWorkshopWorkshopIdRoute
  AppTeacherBoardCourseIdRoute: typeof AppTeacherBoardCourseIdRoute
  AppTeacherExamsExamIdRoute: typeof AppTeacherExamsExamIdRoute
  AppTeacherGradingCourseIdRoute: typeof AppTeacherGradingCourseIdRoute
  AppTeacherKahootGameIdRoute: typeof AppTeacherKahootGameIdRoute
  AppTeacherMonitorExamIdRoute: typeof AppTeacherMonitorExamIdRoute
  AppTeacherWhiteboardsIdRoute: typeof AppTeacherWhiteboardsIdRoute
  AppStudentTutorIndexRoute: typeof AppStudentTutorIndexRoute
  AppStudentWhiteboardsIndexRoute: typeof AppStudentWhiteboardsIndexRoute
  AppTeacherExamsIndexRoute: typeof AppTeacherExamsIndexRoute
  AppTeacherWhiteboardsIndexRoute: typeof AppTeacherWhiteboardsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppTrashRoute: AppTrashRoute,
  AppUnauthorizedRoute: AppUnauthorizedRoute,
  AppVideosRoute: AppVideosRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAcademicRoute: AppAdminAcademicRoute,
  AppAdminAiCronRoute: AppAdminAiCronRoute,
  AppAdminAiPromptsRoute: AppAdminAiPromptsRoute,
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminCoursesRoute: AppAdminCoursesRoute,
  AppAdminEmailSettingsRoute: AppAdminEmailSettingsRoute,
  AppAdminErrorsRoute: AppAdminErrorsRoute,
  AppAdminReportTemplatesRoute: AppAdminReportTemplatesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminStatisticsRoute: AppAdminStatisticsRoute,
  AppAdminSupportRoute: AppAdminSupportRoute,
  AppAdminSupportAssistantRoute: AppAdminSupportAssistantRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppForumCourseIdRoute: AppForumCourseIdRouteWithChildren,
  AppStudentAttendanceRoute: AppStudentAttendanceRoute,
  AppStudentCalendarRoute: AppStudentCalendarRoute,
  AppStudentCertificatesRoute: AppStudentCertificatesRoute,
  AppStudentCoursesRoute: AppStudentCoursesRoute,
  AppStudentExamsRoute: AppStudentExamsRoute,
  AppStudentGradesRoute: AppStudentGradesRoute,
  AppStudentPollsRoute: AppStudentPollsRoute,
  AppStudentProjectsRoute: AppStudentProjectsRoute,
  AppStudentWorkshopsRoute: AppStudentWorkshopsRoute,
  AppSuperadminPricingCalculatorRoute: AppSuperadminPricingCalculatorRoute,
  AppSuperadminSupportRoute: AppSuperadminSupportRoute,
  AppSuperadminSystemRoute: AppSuperadminSystemRoute,
  AppSuperadminTenantsRoute: AppSuperadminTenantsRoute,
  AppTeacherAiCronRoute: AppTeacherAiCronRoute,
  AppTeacherAiPromptsRoute: AppTeacherAiPromptsRoute,
  AppTeacherAttendanceRoute: AppTeacherAttendanceRoute,
  AppTeacherAuditLogsRoute: AppTeacherAuditLogsRoute,
  AppTeacherCalendarRoute: AppTeacherCalendarRoute,
  AppTeacherContentsRoute: AppTeacherContentsRoute,
  AppTeacherCoursesRoute: AppTeacherCoursesRoute,
  AppTeacherGradebookRoute: AppTeacherGradebookRoute,
  AppTeacherPollsRoute: AppTeacherPollsRoute,
  AppTeacherProjectsRoute: AppTeacherProjectsRoute,
  AppTeacherQuestionBankRoute: AppTeacherQuestionBankRoute,
  AppTeacherReportsRoute: AppTeacherReportsRoute,
  AppTeacherStatisticsRoute: AppTeacherStatisticsRoute,
  AppTeacherStudentsRoute: AppTeacherStudentsRoute,
  AppTeacherWorkshopsRoute: AppTeacherWorkshopsRoute,
  AppStudentKahootGameIdRoute: AppStudentKahootGameIdRoute,
  AppStudentProjectProjectIdRoute: AppStudentProjectProjectIdRoute,
  AppStudentReviewExamIdRoute: AppStudentReviewExamIdRoute,
  AppStudentTakeExamIdRoute: AppStudentTakeExamIdRoute,
  AppStudentTutorCourseIdRoute: AppStudentTutorCourseIdRoute,
  AppStudentWhiteboardsIdRoute: AppStudentWhiteboardsIdRoute,
  AppStudentWorkshopWorkshopIdRoute: AppStudentWorkshopWorkshopIdRoute,
  AppTeacherBoardCourseIdRoute: AppTeacherBoardCourseIdRoute,
  AppTeacherExamsExamIdRoute: AppTeacherExamsExamIdRoute,
  AppTeacherGradingCourseIdRoute: AppTeacherGradingCourseIdRoute,
  AppTeacherKahootGameIdRoute: AppTeacherKahootGameIdRoute,
  AppTeacherMonitorExamIdRoute: AppTeacherMonitorExamIdRoute,
  AppTeacherWhiteboardsIdRoute: AppTeacherWhiteboardsIdRoute,
  AppStudentTutorIndexRoute: AppStudentTutorIndexRoute,
  AppStudentWhiteboardsIndexRoute: AppStudentWhiteboardsIndexRoute,
  AppTeacherExamsIndexRoute: AppTeacherExamsIndexRoute,
  AppTeacherWhiteboardsIndexRoute: AppTeacherWhiteboardsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCancelEmailChangeRoute: typeof AuthCancelEmailChangeRoute
  AuthConfirmEmailChangeRoute: typeof AuthConfirmEmailChangeRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCancelEmailChangeRoute: AuthCancelEmailChangeRoute,
  AuthConfirmEmailChangeRoute: AuthConfirmEmailChangeRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AsistenciaRoute: AsistenciaRoute,
  AuthRoute: AuthRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RetoPinRoute: RetoPinRoute,
  VerifyShortCodeRoute: VerifyShortCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
