// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { persistentAuthStorage } from './persistent-storage';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // Storage en IndexedDB (persistentAuthStorage) en vez de
      // localStorage. Chrome Android — y algunos browsers iOS PWA —
      // limpian localStorage cuando la PWA queda en background y el SO
      // presiona memoria; eso expulsaba al usuario al reabrir la app.
      // IndexedDB cae bajo "persistent storage" en la mayoría de
      // browsers y sobrevive ese ciclo de eviction. La capa migra
      // valores existentes de localStorage al primer acceso para no
      // forzar re-login tras el deploy.
      storage: typeof window !== 'undefined' ? persistentAuthStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // PKCE: flujo de auth más robusto, mejor para PWAs en móvil
      // donde un cambio de app puede romper el redirect implícito.
      flowType: 'pkce',
      detectSessionInUrl: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

